apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-init-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-init
  template:
    metadata:
      labels:
        app: nginx-init
    spec:
      initContainers:
      - name: wait-for-svc
        image: busybox:latest
        command: ['sh', '-c', 'until nslookup nginx-init-svc 2>&1 | grep -q "Name:"; do echo waiting for nginx-init-svc; sleep 2; done;']
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
